apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: customer
    service: customer
    app.kubernetes.io/component: customer
    app.kubernetes.io/instance: customer
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: store
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: customer
spec:
  ports:
    - name: http-8080
      port: 8080
      targetPort: 8080
  selector:
    app: customer
  sessionAffinity: None
  type: ClusterIP
