apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: preference
    app.kubernetes.io/component: preference
    app.kubernetes.io/instance: preference
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: store
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: preference
spec:
  lookupPolicy:
    local: false
