apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations: {}
  labels:
    app: config-server
    app.kubernetes.io/component: config-server
    app.kubernetes.io/instance: config-server
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: store
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: config-server
spec:
  lookupPolicy:
    local: false
