apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: gateway
    service: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: gateway
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: store
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: gateway
spec:
  ports:
    - name: http-8080
      port: 8080
      targetPort: 8080
  selector:
    app: gateway
  sessionAffinity: None
  type: ClusterIP
