apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: preference
    service: preference
    app.kubernetes.io/component: preference
    app.kubernetes.io/instance: preference
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: store
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
  name: preference
spec:
  ports:
    - name: http-8080
      port: 8080
      targetPort: 8080
  selector:
    app: preference
  sessionAffinity: None
  type: ClusterIP
